services:
  caddy:
    build:
      dockerfile: ./Dockerfile.caddy
      context: .
    image: caddy-server-manager:latest

    container_name: rproxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "${SM_PORT_START}-${SM_PORT_END}:${SM_PORT_START}-${SM_PORT_END}"
    volumes:
      - ./${SM_CADDY_FILE}:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - frontend/:/srv:ro
    networks:
      - rproxy
      - servers
    environment:
      SM_API_BACKEND: ${SM_API_BACKEND}
    labels:
      - online.nathanswanson.engine=True

  webserver:
    image: ghcr.io/nathanswanson/server-manager:main
    container_name: server-manager
    restart: unless-stopped
    expose:
      - 8000
    environment:
      DOCKER_HOST: tcp://docker-proxy:2375
      SM_DB_CONNECTION: ${SM_SQL_SERVER_PATH}
      SM_API_BACKEND: ${SM_API_BACKEND}
      SM_STATIC_PATH: /data/static/
      SM_SECRET_KEY: ${SM_SECRET_KEY} # password hashing
      SM_PORT_START: ${SM_PORT_START}
      SM_PORT_END: ${SM_PORT_END}
      SM_LOG_PATH: ${SM_LOG_PATH}
      SM_MOUNT_PATH: ${SM_MOUNT_PATH}
    depends_on:
      - docker-proxy
    networks:
      - dockernet
      - rproxy
      - database
    labels:
      - online.nathanswanson.engine=True

  docker-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: always
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1" # allow create/list/inspect/remove containers
      IMAGES: "1" # allow image operations
      VOLUMES: "0" # disallow volume operations (set 1 if needed)
      NETWORKS: "1" # allow network operations
      SERVICES: "0" # disallow swarm services (optional)
      CONFIGS: "0"
      SECRETS: "0"
      SWARM: "0"
      POST: "1"
      EXEC: "1"
    networks:
      - dockernet
    labels:
      - online.nathanswanson.engine=True

  # Use postgres/example user/password credentials

  db:
    image: postgres:18.0
    container_name: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${SM_SQL_SERVER_PASSWORD}
    networks:
      - database
    labels:
      - online.nathanswanson.engine=True

  adminer:
    image: adminer
    container_name: postgres_admin
    restart: always
    ports:
      - 8080:8080
    networks:
      - database
    labels:
      - online.nathanswanson.engine=True

networks:
  rproxy:
    driver: bridge
  dockernet:
    driver: bridge
  database:
    driver: bridge
  servers:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  db-data:
