services:
  webserver:
    build:
      context: ./SM-Backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./SM-Backend:/app
    image: "server-manager:local"
    command: hatch run debugpy --listen 0.0.0.0:5678  -m uvicorn src.server_manager.webservice.webservice:app --reload --host 0.0.0.0 --port 8000
    pull_policy: never
    environment:
      - SM_STATIC_PATH=NULL
      - SM_ENV=DEV
    ports:
      - "5678:5678"
  frontend:
    container_name: frontend
    build:
      context: ./SM-Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./SM-Frontend:/app
      - /app/node_modules # Important: keeps container's node_modules
    networks:
      - rproxy
  caddy:
    ports:
      - "2019:2019" # Expose Caddy's admin port for easier debugging
