services:
  caddy:
    image: caddy:latest
    container_name: rproxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./CaddyFile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - rproxy
    environment:
      CADDY_HOST: ${CADDY_HOST}

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_WEBSOCKET: ${VITE_BACKEND_WEBSOCKET}
        VITE_BACKEND_HOST: ${VITE_BACKEND_HOST}
      ssh:
        - default
    image: server-manager:${TAG}
    container_name: server-manager
    restart: unless-stopped
    expose:
      - 8000
    environment:
      DOCKER_HOST: tcp://docker-proxy:2375
      DB_CONNECTION: ${SQL_SERVER_PATH}
      SM_STATIC_PATH: /data/static/
      CF_API_KEY: ${CF_API_KEY} # curseforge
      SECRET_KEY: ${SECRET_KEY} # password hashing
    depends_on:
      - docker-proxy
    networks:
      - dockernet
      - rproxy
      - database

  docker-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: always
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1"   # allow create/list/inspect/remove containers
      IMAGES: "1"       # allow image operations
      VOLUMES: "0"      # disallow volume operations (set 1 if needed)
      NETWORKS: "1"     # allow network operations
      SERVICES: "0"     # disallow swarm services (optional)
      CONFIGS: "0"
      SECRETS: "0"
      SWARM: "0"
      POST: "1"
      EXEC: "1"
    networks:
      - dockernet

# Use postgres/example user/password credentials

  db:
    image: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${SQL_SERVER_PASSWORD}
    networks:
      - database
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  adminer:
    image: adminer
    container_name: postgres_admin
    restart: always
    ports:
      - 8080:8080
    networks:
      - database


networks:
  rproxy:
    driver: bridge
  dockernet:
    driver: bridge
  database:
    driver: bridge
 
volumes:
  caddy_data:
  caddy_config:
  db-data: