services:
  webserver:
    build:
      context: ./SM-Backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./SM-Backend:/app
      - ./SM-Frontend/dist:/data/static
    image: "server-manager:local"
    command: hatch run default:debug
    pull_policy: never
    environment:
      - SM_STATIC_PATH=/data/static
      - SM_ENV=DEV
      - SM_LOG_LEVEL=DEBUG
    ports:
      - "5678:5678" # python debug
  frontend:
    container_name: frontend
    build:
      context: ./SM-Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./SM-Frontend:/app
      - /app/node_modules # Important: keeps container's node_modules
    networks:
      - rproxy
  caddy:
    ports:
      - "2019:2019" # Expose Caddy's admin port for easier debugging
