apiVersion: v1
kind: Service
metadata:
  namespace: www
  name: server-manager-service
spec:
  selector:
    app: server-manager-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
