apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: www
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      # nodeSelector:
      #   role: core
      # tolerations:
      #   - key: "node-role.kubernetes.io/control-node"
      #     operator: "Exists"
      #     effect: "NoSchedule"
      containers:
        - name: frontend-deployment
          image: frontend-test:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
