apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
  namespace: www
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.81
    path: /volume1/k8s/postgresql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""