apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-manager-deployment
  namespace: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-manager-deployment
  template:
    metadata:
      labels:
        app: server-manager-deployment
    spec:
      containers:
        - name: server-manager
          env:
            - name: SM_ENV
              value: "DEV"
