apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      nodeSelector:
        role: core
      tolerations:
        - key: "node-role.kubernetes.io/control-node"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: "postgresql"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
