apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.nathanswanson.online
spec:
  group: nathanswanson.online
  names:
    plural: tenants
    singular: tenant
    kind: Tenant
    shortNames:
      - tn
  scope: Cluster  
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Specification of the Tenant"
              properties:
                tenantID:
                  type: string
                  description: "Unique identifier for the tenant"
                storageProfile:
                  type: string
                  description: "Storage profile associated with the tenant"
                serverDeployments:
                  type: array
                  description: "List of server deployments for the tenant"
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: "Name of the server deployment"
                      online:
                        type: boolean
                        description: "Indicates if the server deployment is online. sets replicas to 1 if true, 0 if false"