name: Docker Image CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: server-manager

jobs:
  call-backend-artifact:
    uses: nathanswanson/SM-Backend/.github/workflows/actions.yml@main
  call-frontend-artifact:
    uses: nathanswanson/SM-Frontend/.github/workflows/actions.yml@main
  build:
    runs-on: ubuntu-latest
    needs: [call-backend-artifact, call-frontend-artifact]
    if: ${{ needs.call-backend-artifact.result == 'success' && needs.call-frontend-artifact.result == 'success' }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Download Artifacts Backend
        uses: actions/download-artifact@v4
        with:
          name: server-manager-backend
          pattern: "*.zip"
      - name: Download Artifact Frontend
        uses: actions/download-artifact@v4
        with:
          name: server-manager-frontend
          pattern: "*.zip"

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # build-args: |
          #   RUN_ID=${{ github.run_id }}
