name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VITE_BACKEND_HOST: https://home.nathanswanson.online
  VITE_BACKEND_WEBSOCKET: wss://home.nathanswanson.online

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      
      - name: Checkout
        uses: actions/checkout@v5
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push
        uses: docker/build-push-action@v6
        
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: server-manager:latest
          build-args: |
            VITE_BACKEND_HOST=${{env.VITE_BACKEND_HOST}}
            VITE_BACKEND_WEBSOCKET=${{env.VITE_BACKEND_WEBSOCKET}}
