name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: server-manager
  VITE_BACKEND_HOST: https://home.nathanswanson.online
  VITE_BACKEND_WEBSOCKET: wss://home.nathanswanson.online

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          fetch-depth: 0 
      - name: Verify Submodule Contents
        run: |
          echo "Listing contents of the submodule folder..."
          # Replace 'SM_Frontend/' with the actual path, e.g., 'src/api'
          ls -R SM_Frontend/
          echo "Submodule check complete."
      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_BACKEND_HOST=${{env.VITE_BACKEND_HOST}}
            VITE_BACKEND_WEBSOCKET=${{env.VITE_BACKEND_WEBSOCKET}}
